### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by mpoeter**
The documentation stated that 0x0f-0x12 are unused. In the code I found that they are actually define objects with unsorted index tables.

### CODE REVIEW

**Comment by jsteemann** [comment]
Thanks for your PR!
AFAIK object types 0x0f to 0x12 should not be used anymore.
I quickly looked for them and found this commit
```
commit 246ebba9b4219791f6a60c363380d4995ef2afef
Author: Max Neunhoeffer <max@arangodb.com>
Date:   Mon Apr 25 09:14:10 2016 +0200

    Throw away no longer needed types 0x0f-0x12.
```
I don't know at the moment whether these types are in use or not. I have to check with @neunhoef. As you said you found code that still defines them, could you let use know which code exactly? Thanks!

**Comment by jsteemann** [comment]
By the way, in order to accept PRs we have to ask you for signing our [Contributor License Agreement](https://www.arangodb.com/documents/cla.pdf). You can scan and email the pdf file to cla@arangodb.com or send it via fax to +49-221-2722999-88. Sorry for the inconvenience, but once the agreement is there this PR and any following can be merged easily.

**Comment by mpoeter** [comment]
In that case the documentation still needs be updated, because the section "Objects" still mentions 0x0f-0x12 as possible types. In fact, these appearances were the reason I started to search the code in the first place. :-)

I will send you the signed CLA asap.

**Comment by jsteemann** [comment]
Looks like you are right. Adding a simple assertion such as
```
VELOCYPACK_ASSERT(*_start < 0x0f && *_start > 0x12); 
```
to Slice's `head` method proves these types are still in use.

**Comment by jsteemann** [comment]
So your patch is just right!

**Comment by mpoeter** [comment]
I suppose you still need to support these types for backwards compatibility. But do you consider them to be deprecated and therefore discourage their usage?
That is your call - just let me know and I will update my patch accordingly.

**Comment by jsteemann** [comment]
I think it's too early to deprecate these type, as we seem to be using them all over the place.
I think we once had the idea to deprecate and/or remove some of the types (thus the commit), but never actually came to do it. So we better put them back into the docs as they are still in use and properly valid types.
Thanks for spotting this!

**Pull request merged**
